
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  airflow:
    build: .
    user: root
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/db/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/home/airflow/.local/lib/python3.12/site-packages
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - INSD_ANPE_SOURCE_URL=https://burkinafaso.opendataforafrica.org/hejwdte/evolution-des-offres-d-emploi-de-l-anpe-par-r%C3%A9gion-et-type-de-contrat
      - INSD_ANPE_CSV_URL=
      - INSD_ANPE_JSON_URL=
    volumes:
      - .:/opt/airflow
      - ./logs:/opt/airflow/logs
      - ./db:/opt/airflow/db
    ports:
      - "8080:8080"
    command: >
      bash -c "
      set -e;
      mkdir -p /opt/airflow/logs /opt/airflow/db;
      if [ ! -f /opt/airflow/db/airflow.db ]; then
        airflow db init;
      else
        airflow db migrate;
      fi;
      airflow connections create-default-connections || true;
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true;
      airflow webserver --port 8080 &
      exec airflow scheduler
      "
    depends_on:
      - minio

volumes:
  minio_data:
