services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    &airflow-common
    build: .
    user: root
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: n7RgfsYMck_ST5AQbMlmpd9nEA1WeN2yU1b34HzBqSA=
      AIRFLOW__WEBSERVER__SECRET_KEY: airflow-demo-secret-key
      PYTHONPATH: /home/airflow/.local/lib/python3.12/site-packages
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      INSD_ANPE_SOURCE_URL: https://burkinafaso.opendataforafrica.org/hejwdte/evolution-des-offres-d-emploi-de-l-anpe-par-r%C3%A9gion-et-type-de-contrat
      INSD_ANPE_CSV_URL: ""
      INSD_ANPE_JSON_URL: ""
    volumes:
      - .:/opt/airflow
      - ./logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    command: >
      bash -c "
      mkdir -p /opt/airflow/logs &&
      airflow db migrate &&
      airflow connections create-default-connections || true &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true
      "

  airflow-webserver:
    <<: *airflow-common
    container_name: projet-airflow-webserver-1
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
      minio:
        condition: service_started
    ports:
      - "8080:8080"
    command: airflow webserver --port 8080

  airflow-scheduler:
    <<: *airflow-common
    container_name: projet-airflow-scheduler-1
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
      minio:
        condition: service_started
    command: airflow scheduler

volumes:
  minio_data:
  postgres_data:
